services:
  - type: web
    name: mmw-remote-api
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        ffmpeg \
        libavformat-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavutil-dev \
        libavfilter-dev \
        libswscale-dev \
        libswresample-dev \
        pkg-config \
        python3-dev \
        gcc \
        g++
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
